version: '3.8'

services:
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  # myapp:
  #   image: myapp:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings__Redis=redis:6379
  #   depends_on:
  #     - redis

volumes:
  redis_data: